### PR TITLE
fix bug

### LINKED ISSUE #63: [BUG] Crash!!! When Community client is undefined
## Current Behavior 
Crash when community client is undefined.

## Expected Behavior
Not crash when community client is undefined.

## Steps to Reproduce
Suddenly buy  the dataset token on web opening. 

## Suggested Solutions
disable input of buy and sell token modal when community client is undefined.

### PR DESCRIPTION
**Pull request by yeast72**
Fixes #63 

- disabled input text of buy/sell dataset token when community data is undefined.

### CODE REVIEW

File: app/src/components/BuySellModal/BuySellModal.js [hunk 1]
```diff
@@ -80,6 +80,13 @@ class BuySellModal extends React.Component {
   }
 
   async getPrice(type, amount) {
+    // waiting for community is not undefined
```
Comment (evilpeach) [inline app/src/components/BuySellModal/BuySellModal.js]: remove this

File: app/src/components/BuySellModal/BuySellModalRender.js [hunk 2]
```diff
@@ -94,18 +103,25 @@ const Amount = ({ type, amountStatus, symbol, amount, handleChange }) => (
...
+        <Flex alignItems="center" style={{ height: '40px' }}>
+          <DotLoading color="#b1b8e7" size="6px" pd="12px 20px" />
+        </Flex>
+      ) : (
+        <Flex flexDirection="row" alignItems="center" justifyContent="center">
+          <AmountInput
+            type="text"
+            name="amount"
+            value={amount}
+            disabled={disabled}
```
Comment (evilpeach) [inline app/src/components/BuySellModal/BuySellModalRender.js]: disabled is always false??

File: app/src/components/BuySellModal/BuySellModalRender.js [hunk 3]
```diff
@@ -94,18 +103,25 @@ const Amount = ({ type, amountStatus, symbol, amount, handleChange }) => (
...
+            placeholder={true ? '' : 'ex.100'}
```
Comment (evilpeach) [inline app/src/components/BuySellModal/BuySellModalRender.js]:
```
placeholder='ex. 100'
```

File: app/src/components/BuySellModal/BuySellModalRender.js [hunk 4]
```diff
@@ -94,18 +103,25 @@ const Amount = ({ type, amountStatus, symbol, amount, handleChange }) => (
...
+            onChange={e => handleChange(e)}
+          />
+          <SymbolType>{symbol ? symbol : 'Token'}</SymbolType>
```
Comment (evilpeach) [inline app/src/components/BuySellModal/BuySellModalRender.js]:
```
symbol && 'Token'
```
